### ISSUE TITLE
Swipe do not work on Android default browser

### ISSUE THREAD

**Issue by onigetoc** [jofan/Touchy#7]
Swipe do not work on Android default browser.
i tryed many touch script and some do not work like Touchy on Android 4.4.2 default browser.
Tap work, double tap ect but not the swipe.

May be there's some explanation here.
http://stackoverflow.com/questions/2987706/touchend-event-doesnt-work-on-android

**Comment by jofan** [comment]
I blame Google. It works now :)
Thanks!
